# Generated by Django 3.2.6 on 2021-09-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papersdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='keyword',
            field=models.CharField(choices=[('ed-tech', 'ed-tech'), ('sci-fi', 'sci-fi')], default='ed-tech', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
