# Generated by Django 3.2.6 on 2021-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papersdb', '0003_auto_20210902_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='categories',
            field=models.CharField(choices=[('paper', 'paper'), ('book', 'book'), ('book_chapter', 'book_chapter'), ('essay', 'essay')], default='paper', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keyword',
            field=models.CharField(choices=[('ed-tech', 'ed-tech'), ('novel', 'novel'), ('sci-fi', 'sci-fi')], default='ed-tech', max_length=50),
        ),
    ]
