# Generated by Django 3.2.6 on 2021-09-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papersdb', '0005_alter_paper_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
